TYPE=VIEW
query=select `finaldbpos`.`customers`.`id` AS `id`,`finaldbpos`.`customers`.`company` AS `company`,`finaldbpos`.`customers`.`last_name` AS `last_name`,`finaldbpos`.`customers`.`first_name` AS `first_name`,`finaldbpos`.`customers`.`mobile_phone` AS `mobile_phone`,`finaldbpos`.`customers`.`address` AS `address` from `finaldbpos`.`customers`
md5=07199790cd4a876163a1ca4546fb5fbc
updatable=1
algorithm=0
definer_user=
definer_host=
suid=2
with_check_option=0
timestamp=2021-12-19 14:42:05
create-version=2
source=SELECT * FROM customers
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `finaldbpos`.`customers`.`id` AS `id`,`finaldbpos`.`customers`.`company` AS `company`,`finaldbpos`.`customers`.`last_name` AS `last_name`,`finaldbpos`.`customers`.`first_name` AS `first_name`,`finaldbpos`.`customers`.`mobile_phone` AS `mobile_phone`,`finaldbpos`.`customers`.`address` AS `address` from `finaldbpos`.`customers`
mariadb-version=100420
