TYPE=VIEW
query=select `finaldbpos`.`suppliers`.`id` AS `id`,`finaldbpos`.`suppliers`.`company` AS `company`,`finaldbpos`.`suppliers`.`last_name` AS `last_name`,`finaldbpos`.`suppliers`.`first_name` AS `first_name`,`finaldbpos`.`suppliers`.`mobile_phone` AS `mobile_phone`,`finaldbpos`.`suppliers`.`address` AS `address` from `finaldbpos`.`suppliers`
md5=3012e08d21665aab24c06d4a2fc1cabe
updatable=1
algorithm=0
definer_user=
definer_host=
suid=2
with_check_option=0
timestamp=2021-12-19 14:46:26
create-version=2
source=SELECT * FROM suppliers
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `finaldbpos`.`suppliers`.`id` AS `id`,`finaldbpos`.`suppliers`.`company` AS `company`,`finaldbpos`.`suppliers`.`last_name` AS `last_name`,`finaldbpos`.`suppliers`.`first_name` AS `first_name`,`finaldbpos`.`suppliers`.`mobile_phone` AS `mobile_phone`,`finaldbpos`.`suppliers`.`address` AS `address` from `finaldbpos`.`suppliers`
mariadb-version=100420
